### ISSUE TITLE
Manchmal Kartenreset nach renew Session Key bei HD03

### ISSUE THREAD

**Issue by anudanan** [OpenVisionE2/oscam#1]
Ich setze seid Mitte März eine frische HD03 in der oscam ein und habe bis gestern immer wieder mal aktuelle Versionen selbst gebaut und eingesetzt. Bis zu 11510 tritt immer wieder mal ein Rester der HD03 auf, so einmal am Tag im Schnitt. Es wird ein renew Session Key gemacht und dann oft bei der nächste ECM Anfrage kommt ein not found und die Karte meldet einen Code, woraufhin dann ein Karten Reset passiert und dann geht es weiter, Ein ECM scheitert dadurch und es gibt dann eine kurze Bildstörung. Laut vti Forum habe auch andere User das beobachtet.

Kann ich irgendwas debuggen, um bei der Sache mitzuhelfen, die Ursache zu finden?

`019/04/04 06:58:58 69B1A3F2 c (ecm) Kind (1860@000000/0000/EF75/8F:E5644A5D37D57016F8E1AA86C2AC9222): found (299 ms) by hdplus03_(oben)
2019/04/04 06:58:58 711C38BB r (reader) hdplus03_(oben) [nagra merlin] renew Session Key: CAK7
2019/04/04 06:59:13 711C38BB r (reader) hdplus03_(oben) [nagra merlin] (ECM) Reader will be restart now cause: 6F 01 card answer!!!
2019/04/04 06:59:13 69B1A3F2 c (ecm) Kind (1860@000000/0000/EF75/8F:C152298F0F843FAEEEDD357199C9C980): not found (46 ms) by hdplus03_(oben)
2019/04/04 06:59:13 711C38BB r (reader) hdplus03_(oben) [nagra merlin] renew Session Key: CAK7
2019/04/04 06:59:14 711C38BB r (reader) hdplus03_(oben) [nagra merlin] Deactivating card
2019/04/04 06:59:14 711C38BB r (reader) hdplus03_(oben) [nagra merlin] creating thread for device /dev/sci1
2019/04/04 06:59:14 207B094E r (reader) hdplus03_(oben) [nagra merlin] Reader initialized (device=/dev/sci1, detect=cd, mhz=500, cardmhz=368)
2019/04/04 06:59:14 207B094E r (reader) hdplus03_(oben) [nagra merlin] Reader sci internal, detected box type: et9000
2019/04/04 06:59:15 207B094E r (reader) hdplus03_(oben) [nagra merlin] card detected
2019/04/04 06:59:15 207B094E r (reader) hdplus03_(oben) [internal] ATR: 3F FF 95 00 FF 91 81 71 FE 57 00 44 4E 41 53 50 34 31 30 20 52 65 76 51 32 35 17
2019/04/04 06:59:17 207B094E r (reader) hdplus03_(oben) [internal] detected nagra merlin card in CAK7 mode
2019/04/04 06:59:18 207B094E r (reader) hdplus03_(oben) [internal] Rom revision: DNASP410 RevQ25
2019/04/04 06:59:19 207B094E r (reader) hdplus03_(oben) [internal] ready for requests
2019/04/04 06:59:19 207B094E r (reader) hdplus03_(oben) [internal] found card system nagra merlin
2019/04/04 06:59:19 207B094E r (reader) hdplus03_(oben) [nagra merlin] THIS WAS A SUCCESSFUL START ATTEMPT No 1 out of max alloted of 1
2019/04/04 06:59:19 207B094E r (reader) hdplus03_(oben) [nagra merlin] ROM: D N A S P 4 1 0
2019/04/04 06:59:19 207B094E r (reader) hdplus03_(oben) [nagra merlin] REV: R e v Q 2 5
2019/04/04 06:59:19 207B094E r (reader) hdplus03_(oben) [nagra merlin] SER: ############
2019/04/04 06:59:19 207B094E r (reader) hdplus03_(oben) [nagra merlin] CAID: 1860
2019/04/04 06:59:19 207B094E r (reader) hdplus03_(oben) [nagra merlin] Prv.ID: 00 00 34 11 (sysid)
2019/04/04 06:59:19 207B094E r (reader) hdplus03_(oben) [nagra merlin] Provider Sys ID: 34 11 is active to: 2019/05/26
2019/04/04 06:59:19 207B094E r (reader) hdplus03_(oben) [nagra merlin] -----------------------------------------
2019/04/04 06:59:19 207B094E r (reader) hdplus03_(oben) [nagra merlin] |id |tier |valid from |valid to |
2019/04/04 06:59:19 207B094E r (reader) hdplus03_(oben) [nagra merlin] +----+--------+------------+------------+
2019/04/04 06:59:19 207B094E r (reader) hdplus03_(oben) [nagra merlin] |8011|0068 |2019/03/13 |2020/03/13 |
2019/04/04 06:59:19 207B094E r (reader) hdplus03_(oben) [nagra merlin] |8011|0069 |2011/01/21 |2011/01/23 |
2019/04/04 06:59:19 207B094E r (reader) hdplus03_(oben) [nagra merlin] -----------------------------------------
2019/04/04 06:59:19 207B094E r (reader) hdplus03_(oben) [nagra merlin] Prv.ID: 00 00 00 00
2019/04/04 06:59:19 207B094E r (reader) hdplus03_(oben) [nagra merlin] Prv.ID: 00 00 80 11`

**Comment by persianpros** [comment]
Hi there, first please write English and second we're not OSCam developers ;)

This is a mirror and you need to report to http://www.streamboard.tv/wbb2/portal.php

**Comment by anudanan** [comment]
Thanks for your feedback, Now the reoort is here
http://www.streamboard.tv/oscam/ticket/4725
I´ll close here the issue
